# Generated by Django 3.2.7 on 2021-09-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_code_product_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_per_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_per_category',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_per_category',
        ),
    ]
