# Generated by Django 3.2.7 on 2021-09-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_product_product_per_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='id',
        ),
    ]
