# Generated by Django 3.2.7 on 2021-09-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_code_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brands',
        ),
    ]
