# Generated by Django 3.2.7 on 2021-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutriscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=1, unique=True)),
            ],
        ),
    ]
