# Generated by Django 3.2.7 on 2021-11-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_nutriscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutriscore',
            old_name='score',
            new_name='nutriscore',
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.nutriscore'),
        ),
    ]
