# Generated by Django 3.2.7 on 2021-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20211113_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutriscore',
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.ManyToManyField(to='product.Nutriscore'),
        ),
    ]
