# Generated by Django 3.2.7 on 2021-11-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20211113_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutriscore',
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.nutriscore'),
        ),
    ]
