# Generated by Django 3.2.7 on 2021-11-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20211113_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutriscore',
            new_name='nutriscore_id',
        ),
    ]
