# Generated by Django 3.2.7 on 2021-11-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_rename_nutriscore_product_nutriscore_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutriscore_id',
            new_name='nutriscore',
        ),
    ]
