# Generated by Django 3.2.7 on 2021-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_rename_nutriscore_id_product_nutriscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_nutrition_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
