version: 2.1

orbs:
  python: circleci/python@1.2
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: cimg/openjdk:17.0-browsers

    steps:
      - browser-tools/install-chrome
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test
